### ISSUE TITLE
Make public HTTP Wrapper API

### ISSUE THREAD

**Issue by MNF** [SQLStreamStore/SQLStreamStore#110]
In readme it’s said that HTTP Wrapper API is under development. As I have a similar requirement, it will be very interesting to see your current state to use what’s done so far and possibly contribute.
Please  make public HTTP Wrapper API branch.

**Comment by martijnburgers** [comment]
I also have a similar requirement. Did you ever created such an API?

**Comment by thefringeninja** [comment]
See #104 for a dotnet implementation. The code for the server lives in another repo: https://github.com/SQLStreamStore/SQLStreamStore.HAL

**Comment by martijnburgers** [comment]
Yes thanks. Already found it and using it. Works perfectly.

**Comment by damianh** [comment]
Cool!

**Comment by damianh** [comment]
Hope to do a release of these bits soon.

**Comment by damianh** [comment]
This is now part of the main repo. Beta packages are on CI feed.
