### ISSUE TITLE
Are you planning to support snapshots?

### ISSUE THREAD

**Issue by MNF** [SQLStreamStore/SQLStreamStore#111]
snapshots In EventStore can be useful for performance.
Are you planning to support snapshots? If not, why?

**Comment by damianh** [comment]
Hi, 

SqlStreamStore supports _messages_ which is all a SnapShot really is. (This is why I don't call it Sql_Event_Store).  What it does not support, and never will as long as it's a library, is generating messages. That is up to entirely you. A snapshot is just a document projection, so projecting to a stream (limited by count / age) that stores snapshot messages is rather easy (I do this).

There are a couple of patterns:

 1. Store a snapshot into snapshot stream at same time you append events to an aggregate (or every X events or Y interval) via your aggregate repository. 
 2. Asynchronously project a snapshot via subscription.

In both cases rehydration is read snapshot stream backwards by 1 and then read the aggregate stream forwards from the appropriate stream version.

**Comment by damianh** [comment]
Btw, I've updated the readme to point questions to the ddd-cqrs-es slack channel. Cheers.
