### ISSUE TITLE
Support for Competing Consumers / Consumer Group pattern on the subscribers side

### ISSUE THREAD

**Issue by oncicaradupopovici** [SQLStreamStore/SQLStreamStore#114]
Mandatory in a distributed scenario where one would want to scale the workers that subscribe to the Event Store, for let's say, building the read model. 
The pattern guaranties that a message is not delivered to more than one subscriber in the same consumer group.

**Comment by oguzhaneren** [comment]
You can simply skip messages if position less equal then saved position.

**Comment by damianh** [comment]
Hi,

Been thinking hard about this and not going to do this within the library. It could be possibly something that can be connected with a subscriber, but would require additional state management which is going beyond a library into application server realm.

Also to rebuild a read model, I don't think one want competing consumers - you'll want each subscriber to receive each  message.

Happy to discuss the patter further here, but going to close this now with a right to re-open it later.

Cheers
