### ISSUE TITLE
Purge $deleted

### ISSUE THREAD

**Issue by damianh** [SQLStreamStore/SQLStreamStore#130]
When a message or stream is deleted, a message is deleted to the $deleted stream. The primary purpose of this is to allow subscribers or (a future) mirroring capability to handle that. The current design retains these deleted messages indefinitely where as for most cases, one would only want to retain the for a period of time.

Throwing out some thoughts:

 1. Leverage the metadata infra to be able to set a `maxAge` and/or `maxLength`. Currently, the API does not allow direct manipulation of streams whose Id starts with `$` by design. I'd like to keep this in place so this approach would require an explicit API. The potential slight problem is that for `maxAge` the purge happens on read so a `ReadAllStreamForwards(null...)` would be required to actually remove the `$deleted` stream messages. If that never happens... `MaxCount` is handled on append, so that is not a concern.

 2. Expose a specific operation such as `PurgeDeleted(TimeSpan olderThan)` that the host application can invoke on it's own schedule. Should this have it's own implementation or underneath just reads the $deleted stream and let the `MaxAge` purge do it's thing?

**Comment by yreynhout** [comment]
Depending on what $deleted is used for both options will work - (1) being the low maintenance option (2) giving you the greatest control over when's a good time to actually perform the deletion.
Perhaps a `PurgeDeleted(StreamVersion asOf)` could be a useful addition to option 2.

Alternatively, I think the whole `$deleted` stream maintenance should be opt-in at the store level. If I split my streams for e.g. GDPR compliancy where a delete should be an actual delete - never mind that the data remains being visible in the db transaction log until compaction, perhaps the whole `$deleted` stream is rather counter productive.

**Comment by damianh** [comment]
If I make it opt-in at store level, I'd have to record that in the store / meta table to ensure all clients adhere to it. Worth investigating.

Delete is an actual delete though (ignoring the db transaction log).
