### ISSUE TITLE
Postgres 1.2.0-build00028 exception when appending to stream

### ISSUE THREAD

**Issue by krikke999** [SQLStreamStore/SQLStreamStore#150]
Was testing the latest version of Postgres (1.2.0-build00028) but I am getting a "Object reference not set" when appendToStream. Reading from stream did not give an exception.

![image](https://user-images.githubusercontent.com/4253419/44571702-cd319a80-a781-11e8-8a55-00c18e8d16db.png)

Using this store initializer:
`using (var store = new PostgresStreamStore(new PostgresStreamStoreSettings(Settings.Default.ESConnectionString) { Schema = "EventStore".ToLower() }))
`

Also tried with no schema provided to the PostgresStreamStoreSettings. (I also ran the await store.CreateSchema() again.

Also downgraded both packages for SqlStreamStore and SqlStreamStore.Postgres to version 16 => same error.

using docker  image 10.5 of postgres.

I have a public schema and a eventstore schema in postgres db
![image](https://user-images.githubusercontent.com/4253419/44572493-3d412000-a784-11e8-88d6-cd4ce6766401.png)

**Comment by krikke999** [comment]
Ok after debugging the source I saw that the _settings.GetUtcNow() is mandatory...
Now it is working properly.

![image](https://user-images.githubusercontent.com/4253419/44577912-8ef0a700-a792-11e8-9e55-5aea26bf2cef.png)

**Comment by damianh** [comment]
I check the guards, it default to `SystemClock.Default` but if you set explicitly set it to null, it will throw internally.

**Comment by krikke999** [comment]
I used this initializer: using (var store = new PostgresStreamStore(new PostgresStreamStoreSettings(Settings.Default.ESConnectionString) { Schema = "EventStore".ToLower() }))
