### ISSUE TITLE
Use regular merges for PRs

### ISSUE THREAD

**Issue by adamralph** [SQLStreamStore/SQLStreamStore#173]
Using these repo options can make things a bit awkward for contributors:

<img src="https://user-images.githubusercontent.com/677704/45379048-5c063a00-b5ff-11e8-82b2-e4581262b5c1.png" width="494px" />

When a squash/rebase merge is used, the commits which are pushed to master are not those which are on my PR branch

<img src="https://user-images.githubusercontent.com/677704/45378355-82c37100-b5fd-11e8-84bc-679a00433db8.png" width="444px" />

I have a git alias that automatically updates my clone and prunes any branches which have been merged. Since these branches have not been merged, they remain present.

Also, consider that the commits in my PR are GPG signed and are therefore displayed as "Verified" by GitHub:

<img src="https://user-images.githubusercontent.com/677704/45378622-43495480-b5fe-11e8-9415-96b7a467b250.png" width="879px" />

Because of the rebase, a new, joint-authored commit is created on master, which is not GPG signed by me:

<img src="https://user-images.githubusercontent.com/677704/45378605-30368480-b5fe-11e8-981f-887ff38f8c84.png" width="882px" />

I suggest switching off both of these options and using regular merges for PRs.

**Comment by damianh** [comment]
Going to consider it...

**Comment by damianh** [comment]
I liked my svn-like single line history, but you maked good arguments. :)
