### ISSUE TITLE
Recommended method to return ReadAllPage in web api

### ISSUE THREAD

**Issue by MNF** [SQLStreamStore/SQLStreamStore#188]
In Asp.Net Core web api  I wanted to return ReadAllPage and created method

`[HttpGet("ReadAllPageForwards")]          public async Task<ReadAllPage> ReadAllPageForwards(…)`

Then I  found that streamMessages do not include  jsonData. I understand that there is no  string property, but GetJsonData() method should be called instead.

I had to create new class HttpReadAllPage, that duplicates sealed class ReadAllPage , but with a property HttpStreamMessage[] Messages instead of StreamMessage[] and also had to copy HttpStreamMessage class (the library has HttpStreamMessage as internal) and then wrote code to 
convert ReadAllPage to HttpReadAllPage.
It looks a lot of extra work just to receive data from GetJsonData()

Is it expected or there is better way to achieve the same?

**Comment by yreynhout** [comment]
Are you aware of [SQLStreamStore.HAL](https://github.com/SQLStreamStore/SQLStreamStore.HAL) 's existence? I feel you're reinventing the wheel and seriously question why you want to expose stream operations like that. Care to elaborate?

**Comment by MNF** [comment]
@yreynhout, Thank you for your reply. 
I’ve seen [SQLStreamStore.HAL](https://github.com/SQLStreamStore/SQLStreamStore.HAL) repository before and have looked into it again after your advice.
Unfortunately there is no documentation and by reading the code I wasn’t able to understand how to use it. 
E.g [SqlStreamStore.HAL.DevServer](https://github.com/SQLStreamStore/SQLStreamStore.HAL/blob/master/src/SqlStreamStore.HAL.DevServer/Program.cs)
shows how to save multiple messages, but doesn’t show how to read page of data.
I am not familiar enough with HAL (Hypertext Application Language), but I am not sure, that it’s structure will give us any benefits.

In the system we are developing there is a Publisher, that sends events about itineraries(streams) to Event Store(MsSqlStreamStore). Different clients will regularly  pull recent events and extract information that they are interesting in.
Effectively my Event Store Api controller consists of 2 operations wrapping AppendToStream and ReadAllPageForwards methods of StreamStore.
EventStore API and (planning so far) clients are Asp.Net Core web services, running on Kubernetes clusters.

**Comment by thefringeninja** [comment]
There is also the (unreleased) HttpClient which speaks HAL.

Also, the DevServer is just there as an example. It needs a lot more to be production ready.

**Comment by michael-freidgeim-webjet** [comment]
@yreynhout , thank you very much for the example. It is very useful to understand HAL implementation. 

I've struggled a bit with versions of dependencies of Example.csproj and found, that including the example to SQLStreamStore.HAL solution is easier to build and run and will be beneficial to other SQLStreamStore.HAL users.
Please see https://github.com/SQLStreamStore/SQLStreamStore.HAL/pull/22.

That's pity, that I wasn't aware how to use the SQLStreamStore.HAL before. As I've already created my own http wrapper, I will continue to use it. In case we will found any major  issue with my implementation I will consider to use SQLStreamStore.HAL instead.
