### ISSUE TITLE
Transaction  was deadlocked on lock Intermittently 

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [SQLStreamStore/SQLStreamStore#198]
We have  Publisher, that sends events about streams to MsSqlStreamStore saving to Azure SQL database and Client which regularly pull recent events.  
Effectively we are using 2 operations wrapping AppendToStream and ReadAllPageForwards methods of SqlStreamStore. I didn't make any proprietary changes to SQL queries. There are no other applications that working with the database.    

I am using versions
```
 <PackageReference Include="SqlStreamStore" Version="1.1.2" />
    <PackageReference Include="SqlStreamStore.MsSql" Version="1.1.2" />
```
 
Intermittently (753 of 41000 ~2%) we have deadlocked  errors in the log:

```
Transaction (Process ID 205) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction. for StreamId 30223 ,  took 00:00:11.6898945   
"System.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 205)
 was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim.  
 Rerun the transaction.\     at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\   at  
 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\    
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet   
 bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\   at  
 System.Data.SqlClient.SqlDataReader.get_MetaData()\   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior 
 runBehavior, String resetOptionsString)\   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()\   at  
 System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod)\   at  
 System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)\   at  
 System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult)\   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult  
 iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\--- End of stack trace from previous location where  
 exception was thrown ---\   at SqlStreamStore.MsSqlStreamStore.AppendToStreamExpectedVersionAny(SqlConnection connection, SqlTransaction transaction,  
 SqlStreamId sqlStreamId, NewStreamMessage[] messages, CancellationToken cancellationToken)\   at  
 SqlStreamStore.MsSqlStreamStore.RetryOnDeadLock[T](Func`1 operation)\   at SqlStreamStore.MsSqlStreamStore.RetryOnDeadLock[T](Func`1 operation)\   at 
  SqlStreamStore.MsSqlStreamStore.AppendToStreamInternal(String streamId, Int32 expectedVersion, NewStreamMessage[] messages, CancellationToken   
  cancellationToken)\  
```

If needed, I can attach other logs, but they seems similar.

Any ideas how to fix such deadlocks will be appreciated.

**Comment by damianh** [comment]
Can you share with us any sort of repro? Sample code showing how you are doing things would help a lot. Without that it is going to be really hard to diagnose.

**Comment by damianh** [comment]
Ty. Will take a look.

**Comment by MNF** [comment]
I’ve noticed that the similar error was considered as acceptable at 
https://github.com/SQLStreamStore/SQLStreamStore/pull/100#issuecomment-330487232

**Comment by damianh** [comment]
With relational databases under high load these things happen and are usually considered to be a transient error. I'd want to minimise it and doubt that I can completely eliminate.

**Comment by damianh** [comment]
> BTW I noticed that previous version of LoadTests supported both LocalSqlServerDatabase and DockerSqlServerDatabase

FYI SQLLocalDB is back in the load tests.

**Comment by damianh** [comment]
I've taken a look at this and the load test is smashing things as hard as possible. I think the occasional deadlock is unavoidable, should be considered transient and, as there error message says, retry. Question is, should the library retry on your behalf for x number of times?

Typically though in a DDD collaborative app there wouldn't be this amount of contention. Are you seeing this under normal circumstances?

**Comment by damianh** [comment]
Just noting for my self - the error number for deadlock transactions is `1205`.

**Comment by michael-freidgeim-webjet** [comment]
After clone from master 4/12/2018 and using sql V3 I haven't  seen the deadlocks in production.
I am ok to close the issue.

**Comment by damianh** [comment]
That's good to hear. I've pulled your code in from your fork https://github.com/SQLStreamStore/SQLStreamStore/commit/e019dd17a401d7fc8493093568b172ef2a41a82e and been testing it locally - I haven't been able to reproduce it either.

Am going to close, can re-open if issue appears.

Final few questions for now - are you experiencing this sort of load in production that the sample code shows? What number of messages per hour / day are you handling? What is the total number of messages and streams in the store? Are these domain events (i.e. a left-fold) or something else?

Asking because it helps me understand what users of this lib are doing. Cheers :)

**Comment by michael-freidgeim-webjet** [comment]
Our Publisher sends data from legacy MS Sql database to Event Store and then clients (currently 1 but will be a few) pull the data from Event Store and save the relevant information in different storages(e.g. Azure blobs). We have 2 modes -migration of historical data and live feed. Migration mode is a heavy one (we had timeouts and deadlocks) , because we want to publish about 5 million records in a week. Migration may happen more than once for the same database, if it will be found that some  information wasn't published during the previous migration(s). In a live-mode we are adding approximately 10,000 events per day.
Currently we have only one event "ItineraryPublished" and each event overwrites the previous state of the stream. But we consider to add extra events, that will describe changes of the state.
