### ISSUE TITLE
Can  namespaces of StreamStoreAcceptanceTests classes for different providers be different?

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [SQLStreamStore/SQLStreamStore#203]
When trying to add a new test case to LoadTests (from master branch) and refer to StreamStoreAcceptanceTestFixture, I've got an error

Error	CS0433	The type 'StreamStoreAcceptanceTests' exists in both 'SqlStreamStore.MsSql.V3.Tests, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' and 'SqlStreamStore.Postgres.Tests, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'	LoadTests	C:\GitReposD\EventStore\SQLStreamStore\src\LoadTests\Program.cs	

The classes in both projects have the same namespace SqlStreamStore

Is it possible to have different namespaces , such as SqlStreamStore.MsSql and SqlStreamStore.Postgres?

**Comment by damianh** [comment]
The acceptance tests are included in test projects as linked files. This allow us to make a change to one test and have it apply across all stores. We chose this in place of test inheritance which test runners seem to choke on. (Don't have a suggest yet, just explaining the rationale)

**Comment by damianh** [comment]
Am going to remove the references to the test projects in the load test project.
