### ISSUE TITLE
The clean target removes artifacts/.gitignore

### ISSUE THREAD

**Issue by adamralph** [SQLStreamStore/SQLStreamStore#210]
<img src="https://user-images.githubusercontent.com/677704/47953970-dfe7fd00-df84-11e8-8282-2df3dc83f046.png" width="565px" />

Personally I would get rid of the `clean` target. It doesn't _really_ do a "clean", e.g. everything in `bin` and `obj` is left behind. A real clean is `git -fxd`.

Also, it's only a dependency of `default` anyway, so if you run just `./build.sh run-tests` or `./build.sh pack`, the artifacts are not cleaned first, they are just overwritten.

And on Travis CI, `clean` serves no function, because each build is on a clean VM anyway.

FWIW, I no longer have a `clean` target in any of my projects. If you'd like me to send a PR to remove it, just say the word.

**Comment by damianh** [comment]
Yeah lets remove it.
