### ISSUE TITLE
Idea/Suggestion: Make it possible to better guess 'subscription consumer's catched-up state '

### ISSUE THREAD

**Issue by JulianMay** [SQLStreamStore/SQLStreamStore#213]
### Context:
I am trying to make a simple structure for writing readmodel-projections to an sql-database.
While the projection is "catching-up", i don't want to roundtrip sql-database on each handled event, but batch changes to "every 1000 events" for example.
When the projection is "catched-up / live / hot", i want to write to the sql readmodel as soon as possible.

The Catched-up-callback is called (and executed) as soon as the last page is "input-read / buffered" by the subscription. This is before I have handled the events that have been read, and does not really help me adjust the commit/batch-policy (or at least makes it very complicated, with threading, raceconditions, changing policy too early etc...).

### Suggestion:
Have the subscription ( in this example *IAllStreamSubscription* ) expose something like:
```
    ... 
        /// <summary>
        /// The position of the last message in the latest page-read that (at read-time) was the last page in the stream.
        /// This value is not set before a 'last page' has been read.
        /// </summary>
        /// <remarks>
        /// Useful for controlling stuff like 'commit or batch'-strategies for ReadModels etc.
        /// </remarks>
        long? LatestKnownEndOfStreamPosition { get; }
    ...
```

It could be implemented in *AllStreamSubscription.PullAndPush()* like this:
![image](https://user-images.githubusercontent.com/1412348/48194581-b4329180-e34d-11e8-9154-a1eac7c8c97c.png)

I really like how it works (for me at least) - example of this can be found in my 
*ExampleServiceNov2018*
https://github.com/JulianMay/ExampleServiceNov2018/blob/c9dcfd7dd738862f1b57e8ea209b42e56522c6cc/src/ExampleServiceNov2018.ReadService/SqlProjectionSubscription.cs#L87

Thoughts?

**Comment by yreynhout** [comment]
You could use `ReadAllStreamForward` while catching up and only wire up the subscription as soon as `page.IsEnd` is `true` and you've processed this last page (where last page is always a volatile thing that may change upon each requery).

**Comment by JulianMay** [comment]
Tanks Yves - that seems much cleaner and simpler 😄
