### ISSUE TITLE
Postgres On Main Nuget Feed

### ISSUE THREAD

**Issue by mickdelaney** [SQLStreamStore/SQLStreamStore#230]
Hi,

Is there any possibility of getting the postgres package on the main nuget feed. 
maybe as pre-release ? 

We're about to start some major testing using it on a big feature in our app. Would make life easier.
Also are there outstanding issues you are aware of with the PG impl at the moment ? 

Regards

**Comment by damianh** [comment]
`beta.2` prerelease packages on nuget. https://www.nuget.org/packages/SqlStreamStore.Postgres/1.2.0-beta.2  (though it's taking a wee bit of time to show up on indexes.

Closing the issue but please post any feedback here and will re-open if needed. Thanks!

**Comment by mickdelaney** [comment]
thanks!!!
