### ISSUE TITLE
DeterministicGuidGenerator with command guid

### ISSUE THREAD

**Issue by joffreynorsys** [SQLStreamStore/SQLStreamStore#233]
I try to use SQLStreamStore in my cqrs app. My commands have associate guid for idempotent reason in command bus context. So can i use this guid with `DeterministicGuidGenerator` to generate determistic guid for events to store in SQLStreamStore ?  (if my command generate only one event, i use directly the command guid as message id)

**Comment by damianh** [comment]
DeterministicGuidGenerator (originally from https://github.com/LogosBible/Logos.Utility) takes any source as a byte[]. If you want to use your command ID as the source (instead of the event body) I don't see any specific problem with that.
