### ISSUE TITLE
Sqlite implementation

### ISSUE THREAD

**Issue by damianh** [SQLStreamStore/SQLStreamStore#28]

**Comment by damianh** [comment]
Now that the SqlServer implementation is baking out a bit, time to do other storage implementations.

**Comment by dealproc** [comment]
looking into it.  going to have a lot of questions, but will see what i can accomplish.  laying out project structures now, then will open the early pull request on this.

**Comment by dealproc** [comment]
Functionally complete, but needs a massive refactor...
https://github.com/dealproc/SqlStreamStore/tree/sqlite-2

Thinking about two new methods (extension methods) off of DbCommand that would do something like:

```CSharp
var command = default(DbCommand);

// to get the $all stream
var all = command.AllStream();

// to work with a specific stream
var stream5 = command.streams("stream-5");
var meta5 = command.streams("$$stream-5");
```
There would be an underlying class for both the $all stream, and the per stream access. As an example:

```CSharp
public class AllStream {
    DbCommand _command;
    public AllStream(DbCommand command) {
        _command = command;
    }

    public long HeadPosition() {
        // sql statements to read head position from store.
        return (long)command.ExecuteScalar();
    }
}
```

My thinking here is that once the stream or the $all stream is captured, all commands/reads/etc can be performed and it'd all be within the command context.

**Comment by damianh** [comment]
I think we can close this :)
