### ISSUE TITLE
Adapting Microsoft.Data.SqlClient instead of System.Data.SqlClient

### ISSUE THREAD

**Issue by osoykan** [SQLStreamStore/SQLStreamStore#323]
Hi,

After upgrading to `.NetCore3` I get a lot of weird issues in the runtime, not necessarily all related to SSS:) I just complain about  NetCore3 migration in general, sorry for making this issue a bit wailing wall:). 

So, one of them is `timeout` error, during the creation of SSS schema with `streamStore.CreateSchemaIfNotExists();`

So, after lots of investigation, I realized that in netcore3 Microsoft [decided to change System.Data.SqlClient to Microsoft.Data.SqlClient](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/)

> Microsoft.Data.SqlClient The Microsoft.Data.SqlClient package, 
now available in preview on NuGet, will be the flagship data access driver for SQL Server going forward

so underlying SqlClient implementation in NetCore3 is `Microsoft.Data.SqlClient` which causes unidentifiable timeout errors during the migration and I can't even start to the application itself, it always gets network-related exceptions due to connectivity. I think namespace mismatches cause the error even though they have the same functionality(I think?).

So, What I did is, I got the SSS source code and replaced `System.Data.SqlClient` with the 
``` csharp
<ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="1.0.19269.1" />
</ItemGroup>
```
which is new way of handling the Sql connections and  re-build from source-code and replaced the nuget SSS.Mssql.dll.

Now, it works, tests pass and the application starts.

What do you think about it? I could send a PR for that which I already did the change if you approve.

**Comment by damianh** [comment]
That `Microsoft.Data.SqlClient` package came up in discussion recently and I see it has been released recently and it supports `netstandard2.0` so yes we should move to it. Will take a PR and will tag a beta release right after. 👍
