### ISSUE TITLE
Threading/Deadlock/Concurrency Issue?

### ISSUE THREAD

**Issue by wooderz** [SQLStreamStore/SQLStreamStore#379]
Strange one this. When calling `AppendToStream` with expected version of NoStream (it's a new object) I'm getting an issue intermittently where a WrongExpectedStreamException is thrown. This suggests to me the stream already exists? This only happens when I'm load testing and I can't pinpoint it. 

If I wrap the statement in a try/catch block, it seems to never happen! I currently inject IStreamStore as a singleton and build up a PostgresStreamStore in the service provider function. I'm using Connection Pooling. 

I'm considering wrapping it inside a marshal in some fashion (maybe just a lock) but that feels wrong, any other instances of this or ideas that might be causing it?

**Comment by yreynhout** [comment]
It's a known issue with the MySql implementation, but it's news to me with the Postgres one ... I'll try an add a test to reproduce the behavior. As of how much concurrency are you observing this?

**Comment by wooderz** [comment]
Wasn't lots really, about 120 I think. I use Loadster to do the tests, here's the page with the error on. Each test is set to create a new record (using a random identifier in the post body) so each one should be a NewStream

![image](https://user-images.githubusercontent.com/4377107/77956365-a7f3ff00-72c9-11ea-87b6-88d907f38fdd.png)

**Comment by wooderz** [comment]
To be 100% sure I just ran it with a dataset of all unique values for keys for the tenant id and the same problem occurred. Therefore it's definitely not an ID conflict

**Comment by yreynhout** [comment]
Great, was going to ask - makes looking for the needle in the haystack easier since there should be a needle.

**Comment by wooderz** [comment]
Anything I can do to narrow it down? Happy to share my aggregate `Save` method if that's of any help

**Comment by yreynhout** [comment]
If you can share it, that might shed some extra light.

**Comment by bartelink** [comment]
(FWIW `Equinox.Tool` (see https://github.com/jet/equinox#benchmarks and the section just above) is plumbed to run a concurrency test with error and latency metrics using SqlStreamStore - I have not personally used it for some time and don't have much direct interest in mucking with SQL stores atm)

**Comment by yreynhout** [comment]
I've worked on this with @wooderz privately. We found out that his `Guid` based stream identity generation logic was at fault. Every so often it would generate a duplicate value (where a unique one was expected) and cause the _expected_ behaviour around appending to a stream with `ExpectedVersion.NoStream` to kick in.
