### ISSUE TITLE
Performance issue when ReadingAllForwards on MySql

### ISSUE THREAD

**Issue by damianh** [SQLStreamStore/SQLStreamStore#432]
Lifted the current ReadAll sproc to workbench on a sample data set and it appears to be doing a Full Table Scan and results in 5-10 seconds:

![image](https://user-images.githubusercontent.com/57436/87010316-aab69800-c1c6-11ea-8928-818e1c09df26.png)

Simplified the query removing the `CASE` statement results in an Index Range Scan and results in 0s:

![image](https://user-images.githubusercontent.com/57436/87010638-257fb300-c1c7-11ea-99f5-466459180af7.png)

The MSSQL implementation uses independent, non sproc, statements for various ReadAll permutaions, thus changes are non-breaking. However changes to MYSQL spocs will require a schema migration. On the other hand, if I just use standard statements and ingore the sproc, it won't require a schema change.

@thefringeninja Do you see an particular disadvantages to useing standard statements instead of sprocs?

**Comment by thefringeninja** [comment]
Should be fine

**Comment by damianh** [comment]
Simplified the ReadAllForward statements (seperated into `ReadAllForward.sql` and `ReadAllForwardWithData.sql`). However, re-running the test did not yield better performance.
Turns out the mysql optimiser is not picking the right join. Explicitly using `STRAIGHT_JOIN` bypasses the optimiser resulting in a fast result.

- https://dev.mysql.com/doc/refman/8.0/en/join.html
- https://stackoverflow.com/questions/512294/when-to-use-straight-join-with-mysql
