### ISSUE TITLE
Slack link broken

### ISSUE THREAD

**Issue by Beregoz** [SQLStreamStore/SQLStreamStore#502]
Hello, i'm planning on using the library for my project, but it seems like the docs are still missing some parts and the link to join the slack channel is broken. What is the correct way to get support if needed?

**Comment by yreynhout** [comment]
Hi @Beregoz, could you try this link instead: https://ddd-cqrs-es.slack.com/join/shared_invite/zt-m3vf3alt-S3L~YUoIV88wekj6wSNrUQ#/shared-invite/email

**Comment by Beregoz** [comment]
Thank you!
