### ISSUE TITLE
Log level upon disposing subscriptions

### ISSUE THREAD

**Issue by yreynhout** [SQLStreamStore/SQLStreamStore#65]
The log level seems to be `Error` when some subscriptions get disposed. Since disposing subscriptions is expected behavior, it might be useful to lower the log level.

`2017-02-10 14:31:53.635 +01:00 [Error] Error Disposed in <subscription name here/>. It will shut down.`

**Comment by damianh** [comment]
Basically, lowering this https://github.com/damianh/SQLStreamStore/blob/master/src/SqlStreamStore/Subscriptions/StreamSubscription.cs#L256 to a `warning` should be fine? (Or `info` ?)

**Comment by damianh** [comment]
This is fixed https://github.com/damianh/SQLStreamStore/blob/master/src/SqlStreamStore/Subscriptions/StreamSubscription.cs#L264 , right?

**Comment by damianh** [comment]
Re-open if I've misunderstood :)
