### ISSUE TITLE
Testing Subscriptions Performance for Prefetch

### ISSUE THREAD

**Issue by thefringeninja** [SQLStreamStore/SQLStreamStore#82]
Add a performance test for subscriptions with `prefetch = true` and `prefetch = false`.

**Comment by damianh** [comment]
The overload is already there on the subscription API. 

I would suggest
 - loading up the a store with x number of streams with y number of messages per stream.
 - `SubscribeToAll` from `Position.Start` with default prefetch (`true`) which will catch up and time it.
 - Then repeat with prefetch to `false` and time it.

**Comment by damianh** [comment]
You'll get some ideas from https://github.com/SQLStreamStore/SQLStreamStore/blob/master/src/LoadTests/AppendStreamWithMaxCount.cs

**Comment by damianh** [comment]
Subscription use `ReadAllForward` . There is already a "Read All" configurable load test. I've tweaked the load test to prompt to toggle enabling prefetch.

Using these same values in each test:

    Number of streams: 10000
    Number of messages appended: 100,000
    Read page size: 100

...the results were:

| Message Size (KB) | Prefetch On (msg/s) | Prefetch Off (msg/s) |
| --- | --- | --- |
| 1 KB | 32031 | 33670 |
| 10 KB | 2665 | 33512 |

So the performance is highly dependent on message size. Note: this is local / Named Pipes. Over a network would have lower msg/s.

Play around with the settings to see what you can get.

![image](https://user-images.githubusercontent.com/57436/27402002-7d2ac7c2-56c5-11e7-832d-0d8b3380b870.png)
