### ISSUE TITLE
SqlStreamStore.MsSql 1.0.1 is broken

### ISSUE THREAD

**Issue by mihasic** [SQLStreamStore/SQLStreamStore#88]
Default dependency of SqlStreamStore 1.0.1 does not exist, please publish 1.0.1 or a fixed SqlStreamStore.MsSql with reference to 1.0.0 of SqlStreamStore.

**Comment by damianh** [comment]
https://www.nuget.org/packages/SqlStreamStore.MsSql/

![image](https://user-images.githubusercontent.com/57436/29017336-b645f238-7b56-11e7-86c0-9d596fb65df6.png)

Where do you see default dependency of of SqlStreamStore 1.0.1?

**Comment by mihasic** [comment]
In assembly itself

**Comment by damianh** [comment]
wtf

**Comment by damianh** [comment]
crap 

![image](https://user-images.githubusercontent.com/57436/29017520-76a8b3a8-7b57-11e7-8697-6233e76c9b34.png)

**Comment by damianh** [comment]
Will fix tomorrow. Unless you are using .net core in lambda, you don't need this patch update. Stick with 1.0.0

**Comment by mihasic** [comment]
No rush for me at all

**Comment by damianh** [comment]
Fixed in 1.0.2
